import { services } from '@/content/es/business';
import { Breadcrumb, Cta, FinalCta, PageIntro } from '@/components/ui';
import { CapabilityIcon } from '@/components/icons';
import { BreadcrumbSchema, JsonLd, pageMetadata } from '@/lib/seo';
import { site } from '@/config/site';
export const metadata = pageMetadata('Soluciones tecnológicas para empresas', 'Automatización, datos, software, inteligencia artificial y acompañamiento tecnológico para resolver necesidades reales de tu operación.', '/soluciones');
export default function SolutionsPage() {
  return <><div className="container page-bottom-space"><Breadcrumb current="Soluciones" /><PageIntro eyebrow="Cinco capacidades. Una visión de negocio." title="La tecnología empieza por tu problema." description="No todas las empresas necesitan lo mismo. Combinamos capacidades para conectar lo que ya tienes y construir lo que hace falta." />{services.map((service, index) => <section className="service-detail" id={service.id} key={service.id}><div><CapabilityIcon index={index} /><h2>{service.title}</h2><p>{service.short}</p></div><div><h3>Cuando esto pasa en tu empresa</h3><p>{service.problem}</p><h3>Cómo podemos ayudarte</h3><p>{service.action}</p><div className="service-outcome"><h3>Lo que buscamos lograr</h3><p>{service.outcome}</p></div><div className="tool-chips" aria-label="Herramientas posibles">{service.tools.map(tool => <span key={tool}>{tool}</span>)}</div><Cta href={`/diagnostico?interes=${service.id}`} secondary>Hablemos de este reto</Cta></div></section>)}</div><FinalCta /><BreadcrumbSchema items={[{ name: 'Soluciones', path: '/soluciones' }]} /><JsonLd data={{ '@context': 'https://schema.org', '@graph': services.map(service => ({ '@type': 'Service', name: service.title, description: service.action, serviceType: service.title, url: `${site.url}/soluciones#${service.id}`, provider: { '@id': `${site.url}/#organization` }, areaServed: { '@type': 'Country', name: 'Colombia' } })) }} /></>;
}
